#!/bin/env sh

echo "=============================="
echo "  Installing system packages"
echo "=============================="

echo "Installing global packages..."
# TODO: Make a curated list of system packages to install on a fresh system

echo "Installing yay..."
if pacman -Qs yay > /dev/null ; then
  echo "Yay is already installed, moving on..."
else
  rm -rf /opt/yay
  git clone https://aur.archlinux.org/yay.git /opt/yay
  cd /opt/yay
  makepkg -si --noconfirm
fi

echo "Installing yay packages..."
# TODO: make a curated list of yay packages to install on a fresh system
