#! /bin/sh

seq 0 3 | xargs -l1 -I@ picom -b -d :0.@
nitrogen --restore &
sxhkd &

bspc wm -O HDMI-1 DP-1 DVI-D-2


bspc monitor HDMI-1 -d I II III
bspc monitor DP-1 -d IV V VI
bspc monitor DVI-D-2 -d VII VII VIII

bspc config border_width		2
bspc config window_gap			5

bspc config split_ratio			0.52
bspc config focus_follows_pointer	true
bspc config borderless_monocle		false
bspc config gapless_monocle		false

bspc rule -a Ulauncher state=floating border=off
# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off

dex -a &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
