#!/bin/env sh

# Debugging
set -x

source "/etc/libvirt/hooks/kvm.conf"

modprobe -r vfio
modprobe -r vfio_pci
modprobe -r vfio_iommu_type1

sleep 10

virsh nodedev-reattach $VIRSH_GPU_VIDEO
virsh nodedev-reattach $VIRSH_GPU_AUDIO

modprobe amdgpu
modprobe snd_hda_intel

sleep 3

systemctl start sddm.service
