#!/bin/bash

function find_node_ports() {
  local REGEX=$1

  pw-link -io | grep -E "$REGEX" | grep -Ev "monitor_\w+"
}

function notify() {
  local MSG="$@"

  dunstify -a "ps4_audio_passthrough" -u low -i audio-volume-high -h string:x-dunst-stack-tag:ps4_audio_passthrough "$MSG"
}

PS4_PORTS=($(find_node_ports "alsa_input.pci-0000_00_1b.0.analog-stereo(.[0-9]+)?"))
PC_PORTS=($(find_node_ports "alsa_output.pci-0000_00_1b.0.analog-stereo"))

function link() {
  for i in $(seq ${#PS4_PORTS[@]}); do
    local PS4_PORT=${PS4_PORTS[$i - 1]} 
    local PC_PORT=${PC_PORTS[$i - 1]}

    echo "Linking $PS4_PORT to $PC_PORT"
    /usr/bin/pw-link $PS4_PORT $PC_PORT
  done
}

function unlink() {
  for i in $(seq ${#PS4_PORTS[@]}); do
    local PS4_PORT=${PS4_PORTS[$i - 1]} 
    local PC_PORT=${PC_PORTS[$i - 1]}

    echo "Unlinking $PS4_PORT from $PC_PORT"
    /usr/bin/pw-link -d $PS4_PORT $PC_PORT
  done
}

echo "PS4 Ports: ${PS4_PORTS[@]}"
echo "PC Ports: ${PC_PORTS[@]}"

if /usr/bin/pw-link -l | grep -q "${PS4_PORTS[0]}"; then
  notify "Disabling PS4 audio passthrough"
  unlink
else
  notify "Enabling PS4 audio passthrough"
  link
fi
