#!/bin/sh

source "/home/zakku/.config/bspwm/rules.tools"
init $@

WINDOW_NAME=$(window_prop $WINDOW_ID "WM_NAME")

if [[ "$CLASS_NAME" == "ghidra-Ghidra" ]]; then
  if [[ "$WINDOW_NAME" = "win0" ]]; then
    floating "desktop=^1 state=floating center=on border=off"
  fi
else
 skip
fi
