#!/bin/sh

source "/home/zakku/.config/bspwm/rules.tools"
init $@

WINDOW_NAME=$(window_prop $WINDOW_ID "WM_NAME")

output() {
  local ARGS=$@
  echo "desktop=1 $ARGS"
}

floating() {
  local ARGS=$@
  output "state=floating center=on $ARGS"
}

if [[ "$CLASS_NAME" == jetbrains-* ]] || [[ "$CLASS_NAME" == "kotlinx-coroutines-scheduling-CoroutineScheduler\$Worker" ]]; then
  if [[ "$WINDOW_NAME" = "splash" ]]; then
    floating "border=off"
  elif [[ "$WINDOW_NAME" == "Welcome to "* ]]; then
    floating
  elif [[ "$WINDOW_NAME" == "Import "* ]] && [[ "$WINDOW_NAME" == *"Settings" ]]; then
    floating
  elif [[ "$WINDOW_NAME" == *" and Plugin Updates" ]]; then
    floating
  elif [[ "$WINDOW_NAME" == *"User Agreement" ]]; then
    floating
  fi
else
 skip
fi
