#! /bin/sh

source "/home/zakku/.config/bspwm/rules.tools"
init $@

WINDOW_NAME=$(window_info $WINDOW_ID "WM_NAME")

output() {
  local DATA=$@
  echo "$DATA desktop=1"
}

if [[ "$CLASS_NAME" == jetbrains-* ]]; then
  if [[ "$WINDOW_NAME" = "splash" ]]; then
    output "state=floating border=off"
  elif [[ "$WINDOW_NAME" == "Welcome to "* ]]; then
    output "state=floating"
  elif [[ "$WINDOW_NAME" == "Import "* ]] && [[ "$WINDOW_NAME" == *"Settings" ]]; then
    output "state=floating"
  fi
else
 skip
fi
